import { z } from "zod"

const configSchema = z.object({
	BETTER_AUTH_SECRET: z.string(),
	BETTER_AUTH_URL: z.string(),
	DATABASE_URL: z.string(),
	DB_PASSWORD: z.string(),
	OPENFGA_API_URL: z.string(),
	GOOGLE_OAUTH_CLIENT_ID: z.string(),
	GOOGLE_OAUTH_CLIENT_SECRET: z.string(),
	MINIO_ROOT_USER: z.string().default("clairos_admin"),
	MINIO_ROOT_PASSWORD: z.string().default("clairos_storage_dev"),
	MINIO_ENDPOINT: z.string().default("localhost"),
	MINIO_PORT: z.string().default("9000").transform(Number),
	MINIO_USE_SSL: z.string().default("false").transform((v) => v === "true"),
	MINIO_BUCKET: z.string().default("clairos"),
	MINIO_PUBLIC_URL: z.string().default("http://localhost:9000"),
	VAPID_PUBLIC_KEY: z.string(),
	VAPID_PRIVATE_KEY: z.string(),
	VAPID_SUBJECT: z.string().default("mailto:admin@sinclairs.app"),
})

export const Config = configSchema.parse({
	BETTER_AUTH_SECRET: process.env.BETTER_AUTH_SECRET,
	BETTER_AUTH_URL: process.env.BETTER_AUTH_URL,
	DATABASE_URL: process.env.DATABASE_URL,
	DB_PASSWORD: process.env.DB_PASSWORD,
	OPENFGA_API_URL: process.env.OPENFGA_API_URL,
	GOOGLE_OAUTH_CLIENT_ID: process.env.GOOGLE_OAUTH_CLIENT_ID,
	GOOGLE_OAUTH_CLIENT_SECRET: process.env.GOOGLE_OAUTH_CLIENT_SECRET,
	MINIO_ROOT_USER: process.env.MINIO_ROOT_USER,
	MINIO_ROOT_PASSWORD: process.env.MINIO_ROOT_PASSWORD,
	MINIO_ENDPOINT: process.env.MINIO_ENDPOINT,
	MINIO_PORT: process.env.MINIO_PORT,
	MINIO_USE_SSL: process.env.MINIO_USE_SSL,
	MINIO_BUCKET: process.env.MINIO_BUCKET,
	MINIO_PUBLIC_URL: process.env.MINIO_PUBLIC_URL,
	VAPID_PUBLIC_KEY: process.env.VAPID_PUBLIC_KEY,
	VAPID_PRIVATE_KEY: process.env.VAPID_PRIVATE_KEY,
	VAPID_SUBJECT: process.env.VAPID_SUBJECT,
})