/// <reference lib="webworker" />
import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching';
import { registerRoute, NavigationRoute } from 'workbox-routing';
import { NetworkFirst } from 'workbox-strategies';

declare const self: ServiceWorkerGlobalScope & {
	__WB_MANIFEST: Array<any>;
};

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST);

// Cleanup old caches
cleanupOutdatedCaches();

// Navigation fallback for SPA
const navigationRoute = new NavigationRoute(new NetworkFirst({
	cacheName: 'navigations',
	networkTimeoutSeconds: 3,
}), {
	denylist: [/^\/api/, /^\/static/],
});
registerRoute(navigationRoute);

// Handle Push Notifications
self.addEventListener('push', (event) => {
	if (!event.data) return;

	try {
		const payload = event.data.json();
		const { title, body, icon, data } = payload;

		event.waitUntil(
			self.registration.showNotification(title || 'ClairOS', {
				body: body || '',
				icon: icon || '/pwa-192x192.png',
				badge: '/favicon.png',
				data: data || {},
				vibrate: [100, 50, 100],
			} as any)
		);
	} catch (error) {
		console.error('Error receiving push notification:', error);
	}
});

// Handle Notification Click
self.addEventListener('notificationclick', (event) => {
	event.notification.close();

	const urlToOpen = event.notification.data?.url || '/';

	event.waitUntil(
		self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((windowClients) => {
			// If a window is already open with the URL, focus it
			for (const client of windowClients) {
				if (client.url === urlToOpen && 'focus' in client) {
					return client.focus();
				}
			}
			// Otherwise, open a new window
			if (self.clients.openWindow) {
				return self.clients.openWindow(urlToOpen);
			}
		})
	);
});
